##
## Makefile for Tail tools
##

## Rules

.PHONY: all install remote-install clean

all:
	@echo "All done!"


install:
	@echo "Nothing to do locally"

remote-install:
	anchor-copy wpandump.py /opt/anchor/

clean:
	rm -fr __pycache__
	rm -f *~

